[toolchain]
#anchor_version = "0.30.1"    # `anchor-cli` version to use(requires `avm`)
#solana_version = "1.18.17"    # Solana version to use(applies to all Solana tools)

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_demo_test = "BhuwMLdcx6Ux3cia4SyzPk3DprpDhjYBdqcEKjF2UQHr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
